### ISSUE TITLE
Publish to Ansible Galaxy

### ISSUE THREAD

**Issue by jmcvetta** [freedomofpress/ansible-role-beats#23]
This role is great - thanks for creating it!

But I can't find this role published on Ansible Galaxy.  It would be really nice if it were published there, so `requirements.yml` would look like this:

```
- src: freedomofpress.beats
```

Instead of what it currently looks like:

```
- name: freedomofpress.beats
  src: https://github.com/freedomofpress/ansible-role-beats.git
```

**Comment by jmcvetta** [comment]
![ansible galaxy freedomofpress - chromium_148](https://user-images.githubusercontent.com/55682/32447751-854fc542-c33f-11e7-9493-863be79541c1.png)

**Comment by conorsch** [comment]
Glad you find it useful, @jmcvetta! We've been lagging on Galaxy publication, since internally we mostly use submodules to pull in external roles for projects. That's no reason not to publish the role for others to find and browse. I'll do that today, and ping you when it's finished.

**Comment by conorsch** [comment]
All set, @jmcvetta. Thanks for your interest, and let us know if you have any trouble pulling in the role via Galaxy now!

**Comment by jmcvetta** [comment]
I am still unable to pull the role from Galaxy:

```
- downloading role 'beats', owned by freedomofpress
 [WARNING]: - freedomofpress.beats was NOT installed successfully: - sorry, freedomofpress.beats was not found on https://galaxy.ansible.com.
```

**Comment by msheiny** [comment]
hey @jmcvetta -- looks like the role name in galaxy was referencing the old name -- try again now, its working for me

```
$ ansible-galaxy install freedomofpress.beats
- downloading role 'beats', owned by freedomofpress
- downloading role from https://github.com/freedomofpress/ansible-role-beats/archive/master.tar.gz
```

**Comment by jmcvetta** [comment]
@msheiny Awesome - it's working now.  Thanks!

```
- downloading role 'beats', owned by freedomofpress
- downloading role from https://github.com/freedomofpress/ansible-role-beats/archive/master.tar.gz
- extracting freedomofpress.beats to /home/jmcvetta/.ansible/roles/freedomofpress.beats
- freedomofpress.beats (master) was installed successfully
```
